# Important things:
# - need to be able to support any type
# - need to be able to handle booleans
#


can_messages:
  - id: 0x11
    name: "FrontLights"
    schema:
      # will parse the next two bytes
      - type: "uint_16_t"
        name: "throttle"
        default: 0

      # boolean map
      - type: "boolean_map"
        bits:
          0:
            name: "brake"
            default: false
  - name: "SomeOtherModule"
    dbc: "some_message.bdc"
